/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_sekf_ ## ID
#endif

#include <math.h>
#include <casadi/mem.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[18] = {6, 6, 0, 1, 2, 3, 5, 7, 9, 0, 1, 2, 0, 3, 1, 4, 2, 5};
static const casadi_int casadi_s3[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[21] = {6, 6, 0, 2, 4, 6, 8, 10, 12, 0, 3, 1, 4, 2, 5, 0, 3, 1, 4, 2, 5};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

/* x_dot:(x[6],u[3])->(x_dot[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0] ? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1] ? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1] ? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1] ? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int x_dot(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void x_dot_incref(void) {
}

CASADI_SYMBOL_EXPORT void x_dot_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int x_dot_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int x_dot_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* x_dot_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_dot_name_out(casadi_int i){
  switch (i) {
    case 0: return "x_dot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_dot_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_dot_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int x_dot_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* x_dot_functions(void) {
  static casadi_functions fun = {
    x_dot_incref,
    x_dot_decref,
    x_dot_n_in,
    x_dot_n_out,
    x_dot_name_in,
    x_dot_name_out,
    x_dot_sparsity_in,
    x_dot_sparsity_out,
    x_dot_work,
    x_dot
  };
  return &fun;
}
/* P_dot:(x[6],u[3],PU[6x6,9nz],Q[6x6,6nz])->(P_dot[6x6,12nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[2] ? arg[2][3] : 0;
  a0=(a0+a0);
  a1=arg[3] ? arg[3][0] : 0;
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[2] ? arg[2][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a1=arg[2] ? arg[2][5] : 0;
  a1=(a1+a1);
  a2=arg[3] ? arg[3][1] : 0;
  a1=(a1+a2);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[2] ? arg[2][6] : 0;
  if (res[0]!=0) res[0][3]=a1;
  a2=arg[2] ? arg[2][7] : 0;
  a2=(a2+a2);
  a3=arg[3] ? arg[3][2] : 0;
  a2=(a2+a3);
  if (res[0]!=0) res[0][4]=a2;
  a2=arg[2] ? arg[2][8] : 0;
  if (res[0]!=0) res[0][5]=a2;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[3] ? arg[3][3] : 0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a1;
  a1=arg[3] ? arg[3][4] : 0;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a2;
  a2=arg[3] ? arg[3][5] : 0;
  if (res[0]!=0) res[0][11]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int P_dot(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void P_dot_incref(void) {
}

CASADI_SYMBOL_EXPORT void P_dot_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int P_dot_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int P_dot_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* P_dot_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    case 2: return "PU";
    case 3: return "Q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* P_dot_name_out(casadi_int i){
  switch (i) {
    case 0: return "P_dot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* P_dot_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* P_dot_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int P_dot_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* P_dot_functions(void) {
  static casadi_functions fun = {
    P_dot_incref,
    P_dot_decref,
    P_dot_n_in,
    P_dot_n_out,
    P_dot_name_in,
    P_dot_name_out,
    P_dot_sparsity_in,
    P_dot_sparsity_out,
    P_dot_work,
    P_dot
  };
  return &fun;
}
/* correct:(x[6],u[3],y[6],PU[6x6,9nz],R[6x6,6nz])->(dx[6],dPU[6x6,9nz],beta) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a5, a6, a7, a8, a9;
  a0=arg[3] ? arg[3][0] : 0;
  a1=arg[4] ? arg[4][0] : 0;
  a1=(a0+a1);
  a2=casadi_sq(a1);
  a3=arg[3] ? arg[3][3] : 0;
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a2=sqrt(a2);
  a1=(a1/a2);
  a4=(a3*a1);
  a5=arg[3] ? arg[3][4] : 0;
  a6=arg[4] ? arg[4][3] : 0;
  a6=(a5+a6);
  a7=(a3/a2);
  a8=(a6*a7);
  a4=(a4+a8);
  a8=(a4*a1);
  a8=(a3-a8);
  a9=casadi_sq(a8);
  a10=(a4*a7);
  a6=(a6-a10);
  a10=casadi_sq(a6);
  a9=(a9+a10);
  a9=sqrt(a9);
  a8=(a8/a9);
  a8=(a8/a9);
  a10=(a4*a8);
  a1=(a1-a10);
  a1=(a1/a2);
  a10=(a0*a1);
  a11=(a3*a8);
  a10=(a10+a11);
  a11=arg[2] ? arg[2][0] : 0;
  a12=arg[0] ? arg[0][0] : 0;
  a11=(a11-a12);
  a12=(a10*a11);
  a6=(a6/a9);
  a6=(a6/a9);
  a4=(a4*a6);
  a7=(a7-a4);
  a7=(a7/a2);
  a2=(a0*a7);
  a4=(a3*a6);
  a2=(a2+a4);
  a4=arg[2] ? arg[2][3] : 0;
  a9=arg[0] ? arg[0][3] : 0;
  a4=(a4-a9);
  a9=(a2*a4);
  a12=(a12+a9);
  if (res[0]!=0) res[0][0]=a12;
  a12=arg[3] ? arg[3][1] : 0;
  a9=arg[4] ? arg[4][1] : 0;
  a9=(a12+a9);
  a13=casadi_sq(a9);
  a14=arg[3] ? arg[3][5] : 0;
  a15=casadi_sq(a14);
  a13=(a13+a15);
  a13=sqrt(a13);
  a9=(a9/a13);
  a15=(a14*a9);
  a16=arg[3] ? arg[3][6] : 0;
  a17=arg[4] ? arg[4][4] : 0;
  a17=(a16+a17);
  a18=(a14/a13);
  a19=(a17*a18);
  a15=(a15+a19);
  a19=(a15*a9);
  a19=(a14-a19);
  a20=casadi_sq(a19);
  a21=(a15*a18);
  a17=(a17-a21);
  a21=casadi_sq(a17);
  a20=(a20+a21);
  a20=sqrt(a20);
  a19=(a19/a20);
  a19=(a19/a20);
  a21=(a15*a19);
  a9=(a9-a21);
  a9=(a9/a13);
  a21=(a12*a9);
  a22=(a14*a19);
  a21=(a21+a22);
  a22=arg[2] ? arg[2][1] : 0;
  a23=arg[0] ? arg[0][1] : 0;
  a22=(a22-a23);
  a23=(a21*a22);
  a17=(a17/a20);
  a17=(a17/a20);
  a15=(a15*a17);
  a18=(a18-a15);
  a18=(a18/a13);
  a13=(a12*a18);
  a15=(a14*a17);
  a13=(a13+a15);
  a15=arg[2] ? arg[2][4] : 0;
  a20=arg[0] ? arg[0][4] : 0;
  a15=(a15-a20);
  a20=(a13*a15);
  a23=(a23+a20);
  if (res[0]!=0) res[0][1]=a23;
  a23=arg[3] ? arg[3][2] : 0;
  a20=arg[4] ? arg[4][2] : 0;
  a20=(a23+a20);
  a24=casadi_sq(a20);
  a25=arg[3] ? arg[3][7] : 0;
  a26=casadi_sq(a25);
  a24=(a24+a26);
  a24=sqrt(a24);
  a20=(a20/a24);
  a26=(a25*a20);
  a27=arg[3] ? arg[3][8] : 0;
  a28=arg[4] ? arg[4][5] : 0;
  a28=(a27+a28);
  a29=(a25/a24);
  a30=(a28*a29);
  a26=(a26+a30);
  a30=(a26*a20);
  a30=(a25-a30);
  a31=casadi_sq(a30);
  a32=(a26*a29);
  a28=(a28-a32);
  a32=casadi_sq(a28);
  a31=(a31+a32);
  a31=sqrt(a31);
  a30=(a30/a31);
  a30=(a30/a31);
  a32=(a26*a30);
  a20=(a20-a32);
  a20=(a20/a24);
  a32=(a23*a20);
  a33=(a25*a30);
  a32=(a32+a33);
  a33=arg[2] ? arg[2][2] : 0;
  a34=arg[0] ? arg[0][2] : 0;
  a33=(a33-a34);
  a34=(a32*a33);
  a28=(a28/a31);
  a28=(a28/a31);
  a26=(a26*a28);
  a29=(a29-a26);
  a29=(a29/a24);
  a24=(a23*a29);
  a26=(a25*a28);
  a24=(a24+a26);
  a26=arg[2] ? arg[2][5] : 0;
  a31=arg[0] ? arg[0][5] : 0;
  a26=(a26-a31);
  a31=(a24*a26);
  a34=(a34+a31);
  if (res[0]!=0) res[0][2]=a34;
  a34=(a3*a1);
  a31=(a5*a8);
  a34=(a34+a31);
  a31=(a34*a11);
  a35=(a3*a7);
  a36=(a5*a6);
  a35=(a35+a36);
  a36=(a35*a4);
  a31=(a31+a36);
  if (res[0]!=0) res[0][3]=a31;
  a31=(a14*a9);
  a36=(a16*a19);
  a31=(a31+a36);
  a36=(a31*a22);
  a37=(a14*a18);
  a38=(a16*a17);
  a37=(a37+a38);
  a38=(a37*a15);
  a36=(a36+a38);
  if (res[0]!=0) res[0][4]=a36;
  a36=(a25*a20);
  a38=(a27*a30);
  a36=(a36+a38);
  a38=(a36*a33);
  a39=(a25*a29);
  a40=(a27*a28);
  a39=(a39+a40);
  a40=(a39*a26);
  a38=(a38+a40);
  if (res[0]!=0) res[0][5]=a38;
  a0=(a10*a0);
  a38=(a2*a3);
  a0=(a0+a38);
  a0=(-a0);
  if (res[1]!=0) res[1][0]=a0;
  a12=(a21*a12);
  a0=(a13*a14);
  a12=(a12+a0);
  a12=(-a12);
  if (res[1]!=0) res[1][1]=a12;
  a23=(a32*a23);
  a12=(a24*a25);
  a23=(a23+a12);
  a23=(-a23);
  if (res[1]!=0) res[1][2]=a23;
  a10=(a10*a3);
  a2=(a2*a5);
  a10=(a10+a2);
  a10=(-a10);
  if (res[1]!=0) res[1][3]=a10;
  a34=(a34*a3);
  a35=(a35*a5);
  a34=(a34+a35);
  a34=(-a34);
  if (res[1]!=0) res[1][4]=a34;
  a21=(a21*a14);
  a13=(a13*a16);
  a21=(a21+a13);
  a21=(-a21);
  if (res[1]!=0) res[1][5]=a21;
  a31=(a31*a14);
  a37=(a37*a16);
  a31=(a31+a37);
  a31=(-a31);
  if (res[1]!=0) res[1][6]=a31;
  a32=(a32*a25);
  a24=(a24*a27);
  a32=(a32+a24);
  a32=(-a32);
  if (res[1]!=0) res[1][7]=a32;
  a36=(a36*a25);
  a39=(a39*a27);
  a36=(a36+a39);
  a36=(-a36);
  if (res[1]!=0) res[1][8]=a36;
  a1=(a11*a1);
  a8=(a4*a8);
  a1=(a1+a8);
  a1=(a1*a11);
  a9=(a22*a9);
  a19=(a15*a19);
  a9=(a9+a19);
  a9=(a9*a22);
  a1=(a1+a9);
  a20=(a33*a20);
  a30=(a26*a30);
  a20=(a20+a30);
  a20=(a20*a33);
  a1=(a1+a20);
  a11=(a11*a7);
  a6=(a4*a6);
  a11=(a11+a6);
  a11=(a11*a4);
  a1=(a1+a11);
  a22=(a22*a18);
  a17=(a15*a17);
  a22=(a22+a17);
  a22=(a22*a15);
  a1=(a1+a22);
  a33=(a33*a29);
  a28=(a26*a28);
  a33=(a33+a28);
  a33=(a33*a26);
  a1=(a1+a33);
  if (res[2]!=0) res[2][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int correct(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void correct_incref(void) {
}

CASADI_SYMBOL_EXPORT void correct_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int correct_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int correct_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT const char* correct_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    case 2: return "y";
    case 3: return "PU";
    case 4: return "R";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* correct_name_out(casadi_int i){
  switch (i) {
    case 0: return "dx";
    case 1: return "dPU";
    case 2: return "beta";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* correct_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* correct_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int correct_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* correct_functions(void) {
  static casadi_functions fun = {
    correct_incref,
    correct_decref,
    correct_n_in,
    correct_n_out,
    correct_name_in,
    correct_name_out,
    correct_sparsity_in,
    correct_sparsity_out,
    correct_work,
    correct
  };
  return &fun;
}
/* cond:(x[6],u[3],PU[6x6,9nz],R[6x6,6nz])->(cond) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=INFINITY;
  a1=arg[2] ? arg[2][4] : 0;
  a2=arg[3] ? arg[3][3] : 0;
  a1=(a1+a2);
  a2=arg[2] ? arg[2][0] : 0;
  a3=arg[3] ? arg[3][0] : 0;
  a2=(a2+a3);
  a3=(a1+a2);
  a4=casadi_sq(a3);
  a5=4.;
  a2=(a2*a1);
  a1=arg[2] ? arg[2][3] : 0;
  a1=casadi_sq(a1);
  a2=(a2-a1);
  a2=(a5*a2);
  a4=(a4-a2);
  a4=sqrt(a4);
  a2=(a3-a4);
  a1=2.;
  a2=(a2/a1);
  a2=fabs(a2);
  a6=casadi_fmin(a0,a2);
  a3=(a3+a4);
  a3=(a3/a1);
  a3=fabs(a3);
  a6=casadi_fmin(a6,a3);
  a4=arg[2] ? arg[2][6] : 0;
  a7=arg[3] ? arg[3][4] : 0;
  a4=(a4+a7);
  a7=arg[2] ? arg[2][1] : 0;
  a8=arg[3] ? arg[3][1] : 0;
  a7=(a7+a8);
  a8=(a4+a7);
  a9=casadi_sq(a8);
  a7=(a7*a4);
  a4=arg[2] ? arg[2][5] : 0;
  a4=casadi_sq(a4);
  a7=(a7-a4);
  a7=(a5*a7);
  a9=(a9-a7);
  a9=sqrt(a9);
  a7=(a8-a9);
  a7=(a7/a1);
  a7=fabs(a7);
  a6=casadi_fmin(a6,a7);
  a8=(a8+a9);
  a8=(a8/a1);
  a8=fabs(a8);
  a6=casadi_fmin(a6,a8);
  a9=arg[2] ? arg[2][8] : 0;
  a4=arg[3] ? arg[3][5] : 0;
  a9=(a9+a4);
  a4=arg[2] ? arg[2][2] : 0;
  a10=arg[3] ? arg[3][2] : 0;
  a4=(a4+a10);
  a10=(a9+a4);
  a11=casadi_sq(a10);
  a4=(a4*a9);
  a9=arg[2] ? arg[2][7] : 0;
  a9=casadi_sq(a9);
  a4=(a4-a9);
  a5=(a5*a4);
  a11=(a11-a5);
  a11=sqrt(a11);
  a5=(a10-a11);
  a5=(a5/a1);
  a5=fabs(a5);
  a6=casadi_fmin(a6,a5);
  a10=(a10+a11);
  a10=(a10/a1);
  a10=fabs(a10);
  a6=casadi_fmin(a6,a10);
  a1=1.0000000000000001e-05;
  a6=(a6<a1);
  a1=(a6?a0:0);
  a6=(!a6);
  a11=-INFINITY;
  a11=casadi_fmax(a11,a2);
  a11=casadi_fmax(a11,a3);
  a11=casadi_fmax(a11,a7);
  a11=casadi_fmax(a11,a8);
  a11=casadi_fmax(a11,a5);
  a11=casadi_fmax(a11,a10);
  a0=casadi_fmin(a0,a2);
  a0=casadi_fmin(a0,a3);
  a0=casadi_fmin(a0,a7);
  a0=casadi_fmin(a0,a8);
  a0=casadi_fmin(a0,a5);
  a0=casadi_fmin(a0,a10);
  a11=(a11/a0);
  a6=(a6?a11:0);
  a1=(a1+a6);
  if (res[0]!=0) res[0][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int cond(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void cond_incref(void) {
}

CASADI_SYMBOL_EXPORT void cond_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cond_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int cond_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* cond_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    case 2: return "PU";
    case 3: return "R";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cond_name_out(casadi_int i){
  switch (i) {
    case 0: return "cond";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cond_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cond_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cond_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* cond_functions(void) {
  static casadi_functions fun = {
    cond_incref,
    cond_decref,
    cond_n_in,
    cond_n_out,
    cond_name_in,
    cond_name_out,
    cond_sparsity_in,
    cond_sparsity_out,
    cond_work,
    cond
  };
  return &fun;
}
/* P_init:()->(P0[6x6,9nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int P_init(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void P_init_incref(void) {
}

CASADI_SYMBOL_EXPORT void P_init_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int P_init_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int P_init_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* P_init_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* P_init_name_out(casadi_int i){
  switch (i) {
    case 0: return "P0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* P_init_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* P_init_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int P_init_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* P_init_functions(void) {
  static casadi_functions fun = {
    P_init_incref,
    P_init_decref,
    P_init_n_in,
    P_init_n_out,
    P_init_name_in,
    P_init_name_out,
    P_init_sparsity_in,
    P_init_sparsity_out,
    P_init_work,
    P_init
  };
  return &fun;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
